newsletter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import MailingDetailView

urlpatterns = [
    path("create/", views.CreateMailingView.as_view(), name="create_mailing"),
    path(
        "statistics/", views.UserMailingReportsView.as_view(), name="mailing_statistics"
    ),
    path("contacts/", views.ContactView.as_view(), name="contacts"),
    path("recipient/", views.RecipientListView.as_view(), name="recipient_list"),
    path(
        "recipient/create/",
        views.RecipientCreateView.as_view(),
        name="recipient_create",
    ),
    path(
        "recipient/<int:pk>/update/",
        views.RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient/<int:pk>/delete/",
        views.RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path("messages/", views.MessageListView.as_view(), name="message_list"),
    path("messages/create/", views.MessageCreateView.as_view(), name="message_create"),
    path(
        "messages/<int:pk>/update/",
        views.MessageUpdateView.as_view(),
        name="message_update",
    ),
    path(
        "messages/<int:pk>/delete/",
        views.MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailings/<int:pk>/update/",
        views.MailingUpdateView.as_view(),
        name="mailing_update",
    ),
    path(
        "mailings/<int:pk>/delete/",
        views.MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path(
        "mailings/<int:mailing_id>/start/",
        views.MailingStartView.as_view(),
        name="mailing_start",
    ),
    path(
        "mailings/<int:mailing_id>/detail/",
        MailingDetailView.as_view(),
        name="mailing_detail",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendsphere/urls.py
from django.contrib import admin
from django.urls import include, path
from newsletter import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("newsletter/", include("newsletter.urls")),
    path("users/", include("users.urls")),
    path("", views.HomeView.as_view(), name="home"),
    path("tinymce/", include("tinymce.urls")),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views

# app_name = 'users'


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register, name="register"),
    path("confirm/<str:token>/", views.confirm_email, name="confirm_email"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

newsletter/models.py
from django.conf import settings
from django.db import models


class Recipient(models.Model):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255, verbose_name="Ф.И.О.")
    comment = models.TextField(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name="Тема письма")
    body = models.TextField(verbose_name="Содержание")

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("created", "Создана"),
        ("running", "Запущена"),
        ("completed", "Завершена"),
    ]

    start_time = models.DateTimeField(verbose_name="Дата и время первой отправки")
    end_time = models.DateTimeField(verbose_name="Дата и время окончания отправки")
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="created", verbose_name="Статус"
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Сообщение",
    )
    recipients = models.ManyToManyField(Recipient, verbose_name="Получатели")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        if self.message:
            return f"Рассылка {self.message.subject} ({self.status})"
        else:
            return f"Рассылка (Без сообщения) ({self.status})"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"


class MailingAttempt(models.Model):
    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка"
    )
    attempt_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время попытки"
    )
    status = models.CharField(
        max_length=20,
        choices=[("success", "Успешно"), ("failed", "Не успешно")],
        verbose_name="Статус",
    )
    response = models.TextField(blank=True, verbose_name="Ответ почтового сервера")

    def __str__(self):
        return f"Попытка {self.id} для рассылки {self.mailing.id}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15, blank=True, null=True)
    message = models.TextField()
    objects = models.Manager()

    def __str__(self):
        return self.name

newsletter/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from .models import Mailing, Message, Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ("email", "full_name", "comment")


class MessageForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(attrs={"cols": 80, "rows": 30}))

    class Meta:
        model = Message
        fields = ["subject", "body"]


class MailingForm(forms.ModelForm):
    recipients = forms.ModelMultipleChoiceField(
        queryset=Recipient.objects.all(),
        label="Получатели",
        widget=forms.SelectMultiple(attrs={"class": "form-select"}),
        required=False,
    )

    start_time = forms.DateTimeField(
        label="Дата и время первой отправки",
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
    )

    end_time = forms.DateTimeField(
        label="Дата и время окончания отправки",
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
    )

    class Meta:
        model = Mailing
        fields = ["start_time", "end_time", "recipients", "message", "is_active"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields["recipients"].initial = self.instance.recipients.all()

newsletter/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.mail import send_mail
from django.db.models import Count, Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import MailingForm, MessageForm, RecipientForm
from .models import Contact, Mailing, MailingAttempt, Message, Recipient


class HomeView(View):
    def get(self, request):
        cache_key = "home_view_stats"
        stats = cache.get(cache_key)

        if stats is None:
            total_mailings = Mailing.objects.count()
            active_mailings = Mailing.objects.filter(status="running").count()
            unique_recipients = Recipient.objects.count()
            stats = {
                "total_mailings": total_mailings,
                "active_mailings": active_mailings,
                "unique_recipients": unique_recipients,
            }

            cache.set(cache_key, stats, timeout=300)

        return render(request, "newsletter/home.html", stats)


class CreateMailingView(View):
    def get(self, request):
        form = MailingForm()
        messages_list = Message.objects.all()
        all_recipients = Recipient.objects.all()

        create_message_url = reverse("message_create")
        create_recipient_url = reverse("recipient_create")

        return render(
            request,
            "newsletter/create_mailing.html",
            {
                "form": form,
                "messages": messages_list,
                "recipients": all_recipients,
                "create_message_url": create_message_url,
                "create_recipient_url": create_recipient_url,
            },
        )

    def post(self, request):
        form = MailingForm(request.POST, request.FILES)
        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.owner = request.user
            mailing.status = "created"
            mailing.save()

            selected_recipients = form.cleaned_data["recipients"]
            mailing.recipients.set(selected_recipients)

            return redirect("mailing_list")
        else:
            messages_list = Message.objects.all()
            all_recipients = Recipient.objects.all()
            create_message_url = reverse("message_create")
            create_recipient_url = reverse("recipient_create")
            return render(
                request,
                "newsletter/create_mailing.html",
                {
                    "form": form,
                    "messages": messages_list,
                    "recipients": all_recipients,
                    "create_message_url": create_message_url,
                    "create_recipient_url": create_recipient_url,
                },
            )


class MailingStartView(View):
    def get(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, pk=mailing_id)
        mailing.status = "running"
        mailing.save()
        return redirect("mailing_detail", mailing_id=mailing_id)


def send_mailing(request, pk):
    mailing = get_object_or_404(Mailing, id=pk)
    recipients = mailing.recipients.all()

    for recipient in recipients:
        try:
            send_mail(
                mailing.message.subject,
                mailing.message.body,
                settings.EMAIL_HOST_USER,
                [recipient.email],
                fail_silently=False,
            )

            MailingAttempt.objects.create(
                mailing=mailing,
                status="success",
                response="Сообщение успешно отправлено",
            )

            messages.success(
                request, f"Сообщение отправлено получателю {recipient.email}"
            )

        except Exception as e:
            MailingAttempt.objects.create(
                mailing=mailing,
                status="failed",
                response=str(e),
            )
            messages.error(
                request,
                f"Ошибка при отправке сообщения получателю {recipient.email}: {str(e)}",
            )

    return redirect("mailing_list")


class UserMailingReportsView(LoginRequiredMixin, View):
    template_name = "newsletter/mailing_statistics.html"

    def get(self, request):
        user = request.user
        cache_key = f"user_report_{user.id}"
        user_report = cache.get(cache_key)

        if user_report is None:
            user_report = MailingAttempt.objects.filter(mailing__owner=user).aggregate(
                total_sent=Count("id"),
                successful_attempts=Count("id", filter=Q(status="success")),
                failed_attempts=Count("id", filter=Q(status="failed")),
            )
            cache.set(cache_key, user_report, timeout=300)

        context = {
            "user_report": user_report,
        }
        return render(request, self.template_name, context)


class ContactView(LoginRequiredMixin, View):
    def get(self, request):
        contacts = Contact.objects.all()
        return render(request, "newsletter/contacts.html", {"contacts": contacts})

    def post(self, request):
        name = request.POST.get("name")
        return HttpResponse(f"Спасибо, {name}! Ваше сообщение получено.")


class RecipientListView(ListView):
    model = Recipient
    template_name = "newsletter/recipient/recipient_list.html"
    context_object_name = "recipients"


class RecipientCreateView(CreateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "newsletter/recipient/recipient_create.html"
    success_url = reverse_lazy("recipient_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipientUpdateView(UpdateView):
    model = Recipient
    form_class = RecipientForm
    template_name = "newsletter/recipient/recipient_update.html"
    success_url = reverse_lazy("recipient_list")


class RecipientDeleteView(DeleteView):
    model = Recipient
    template_name = "newsletter/recipient/recipient_delete.html"
    success_url = reverse_lazy("recipient_list")


class MessageListView(ListView):
    model = Message
    template_name = "newsletter/messages/message_list.html"
    context_object_name = "messages"


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = "newsletter/messages/message_create.html"
    success_url = reverse_lazy("message_list")


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    template_name = "newsletter/messages/message_update.html"
    success_url = reverse_lazy("message_list")


class MessageDeleteView(DeleteView):
    model = Message
    template_name = "newsletter/messages/message_delete.html"
    success_url = reverse_lazy("message_list")


class MailingListView(ListView):
    model = Mailing
    template_name = "newsletter/mailings/mailing_list.html"
    context_object_name = "mailings"


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = "newsletter/mailings/create_mailing.html"
    success_url = reverse_lazy("mailing_list")


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "newsletter/mailings/mailing_update.html"
    success_url = reverse_lazy("mailing_list")


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = "newsletter/mailings/mailing_delete.html"
    success_url = reverse_lazy("mailing_list")


class MailingDetailView(View):
    def get(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, pk=mailing_id)
        return render(
            request, "newsletter/mailings/mailing_detail.html", {"mailing": mailing}
        )

newsletter/templates/newsletter/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Магазин{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<header>
    {% include 'newsletter/menu.html' %}
</header>

<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SendSphere
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>

</div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

newsletter/templates/newsletter/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SendSphere</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% extends 'newsletter/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1>Контактная информация</h1>
    <ul>
        {% for contact in contacts %}
        <li>
            <strong>{{ contact.name }}</strong><br>
            Email: {{ contact.email }}<br>
            Телефон: {{ contact.phone }}<br>
            Сообщение:
            <pre>{{ contact.message }}</pre>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>123121541234</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>г.Курск 305000</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

newsletter/templates/newsletter/create_mailing.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Страница создания рассылок</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% extends 'newsletter/base.html' %}

{% block title %}Страница создания рассылок{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="text-center mb-4">Создание новой рассылки</h2>
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Сообщение:</label>
                    {{ form.message }}
                    <a href="{% url 'message_create' %}" class="btn btn-primary btn-sm mt-2">Создать сообщение</a>
                    <a href="{% url 'message_list' %}" class="btn btn-primary btn-sm mt-2">Управление сообщениями</a>
                </div>
                <div class="mb-3">
                    <label class="form-label">Получатели:</label>
                    {{ form.recipients }}
                    <a href="{% url 'recipient_create' %}" class="btn btn-primary btn-sm mt-2">Создать получателя</a>
                    <a href="{% url 'recipient_list' %}" class="btn btn-primary btn-sm mt-2">Управление получателями</a>
                </div>
                <div class="mb-3">
                    <label for="start_time" class="form-label">Дата и время первой отправки:</label>
                    {{ form.start_time }}
                </div>

                <div class="mb-3">
                    <label for="end_time" class="form-label">Дата и время окончания отправки:</label>
                    {{ form.end_time }}
                </div>

                <div class="mb-3 form-check">
                    {{ form.is_active }}
                    <label class="form-check-label" for="id_is_active">Активна</label>
                </div>
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'mailing_list' %}" class="btn btn-primary btn-sm mt-2">Список рассылок</a>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}
</body>
</html>

newsletter/templates/newsletter/home.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% extends 'newsletter/base.html' %}


{% block title %}Главная страница{% endblock %}

{% block content %}
<div class="hero">
    <h1 class="display-4">Добро пожаловать в SendSphere!</h1>
    <p class="lead">Эффективные Email Рассылки для вашего бизнеса</p>
</div>
{% load cache %}
{% cache 600 my_cache_key %}
<div class="container text-center my-5">
    <div class="row">
        <div class="col-md-4 feature-item">
            <div class="border rounded p-3">
                <h5>Общее количество рассылок:</h5>
                <mark>{{ total_mailings }}</mark>
            </div>
        </div>
        <div class="col-md-4 feature-item">
            <div class="border rounded p-3">
                <h5>Количество активных рассылок:</h5>
                <mark>{{ active_mailings }}</mark>
            </div>
        </div>
        <div class="col-md-4 feature-item">
            <div class="border rounded p-3">
                <h5>Количество уникальных получателей:</h5>
                <mark>{{ unique_recipients }}</mark>
            </div>
        </div>
    </div>
</div>
{% endcache %}
<div class="container feature-text">
    <h3>Что мы предлагаем:</h3>
    <p>Добро пожаловать на наш сайт, посвящённый эффективным email рассылкам! Мы предлагаем инновационные решения для
        вашего бизнеса, позволяя вам легко и быстро доставлять важные сообщения и акции прямо в почтовые ящики ваших
        клиентов. Наша платформа предоставляет мощные инструменты для создания привлекательных рассылок, таргетирования
        аудитории и анализа результатов.</p>
    <ul>
        <li>Налаживать персонализированную коммуникацию с клиентами.</li>
        <li>Увеличивать уровень вовлеченности и лояльности.</li>
        <li>Отслеживать эффективность кампаний в реальном времени.</li>
    </ul>
    <p>Начните сегодня и преобразите свои маркетинговые стратегии с помощью корректно настроенных email рассылок!</p>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
{% endblock %}
</html>

newsletter/templates/newsletter/mailing_statistics.html
{% extends 'newsletter/base.html' %}

{% block title %}Статистика рассылок{% endblock %}

{% block content %}
<h1>Ваши отчеты по рассылкам</h1>

{% if user_report %}
{% load cache %}
{% cache 600 my_cache_key %}
<table class="table">
    <thead>
    <tr>
        <th>Всего отправлено</th>
        <th>Успешных попыток</th>
        <th>Неудачных попыток</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ user_report.total_sent }}</td>
        <td>{{ user_report.successful_attempts }}</td>
        <td>{{ user_report.failed_attempts }}</td>
    </tr>
    </tbody>
</table>
{% endcache %}
{% else %}
<p>У вас пока нет данных для отчетов.</p>
{% endif %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}

newsletter/templates/newsletter/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <h5 class="my-2 me-4 font-weight-normal">SendSphere</h5>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="me-auto d-flex">
                <a class="p-3 btn btn-outline-primary me-2" href="/">Главная</a>
                <a class="p-3 btn btn-outline-primary me-2" href="/newsletter/contacts/">Контакты</a>
                {% if user.is_authenticated %}
                <a class="p-3 btn btn-outline-primary me-2" href="/newsletter/create/">Создать рассылку</a>
                <a class="p-3 btn btn-outline-primary" href="/newsletter/statistics/">Статистика</a>
                {% endif %}
            </div>
            <div class="d-flex">
                {% if user.is_authenticated %}
                <div class="d-flex align-items-center">
                    <span class="me-2">Добро пожаловать: {{ user.username }}!</span>
                    <a class="btn btn-outline-primary me-2" href="/users/password_reset/">Сменить пароль</a>
                    <a class="btn btn-outline-primary" href="/users/logout/">Выйти</a>
                </div>
                {% else %}
                <a class="p-3 btn btn-outline-primary me-2" href="/users/login/">Войти</a>
                <a class="p-3 btn btn-outline-primary" href="/users/register/">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
</div>
</nav>

newsletter/templates/newsletter/recipient_list.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список клиентов</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<h1>Список получателей</h1>
<a href="{% url 'recipient_create' %}" class="btn btn-primary mb-3">Добавить нового</a>
<ul class="list-group">
{% for recipient in recipients %}
    <li class="list-group-item">
        {{ recipient.email }} ({{ recipient.fio }})
        <div class="mt-2">
            <a href="{% url 'recipient_update' recipient.id %}" class="btn btn-primary btn-sm">Редактировать</a>
            <a href="{% url 'recipient_delete' recipient.id %}" class="btn btn-danger btn-sm">Удалить</a>
        </div>
    </li>
{% endfor %}
</ul>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
{% endblock %}
</html>